services:
  postgres_DB: 
    image: postgres
    container_name: postgres_DB
    restart: always
    environment:
      POSTGRES_PASSWORD: 13771377
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres_DB
    ports:
      - "8080:8080"
    
volumes:
  pgdata: 
